### ISSUE TITLE
Condensers create damaged items 

### ISSUE THREAD

**Issue by MaPePeR** [sinkillerj/ProjectE#1047]
https://reddit.com/r/feedthebeast/comments/3o5gjr/rftools_and_projecte_i_dont_know_what_i_expected/cvuff6d

I don't think you are supposed to be able to duplicate damaged tools.
(I think this is fixed by #1015 or #1036)

**Comment by sinkillerj** [comment]
Thought we already had a open issue for this but I guess not.

**Comment by MaPePeR** [comment]
Didn't remember or find one - but there might be

**Comment by williewillus** [comment]
umm isn't it supposed to check the NBT Whitelist for things like this? And that system has been/should be fully working unless it was mucked around with :p

**Comment by MaPePeR** [comment]
Damage is different than nbt. The problem is, that everything uses the same single getEmc method that also does the damage calculation. 

That was probably always the case, because nobody mocked with it. 
I think I fixed this by accident in the PRs mentioned above

**Comment by Mysteryem** [comment]
This is still an issue in ProjectE-1.7.10-PE1.10.0. While you cannot create damaged items in transmutation tablets, you can still create them in energy condensers.
