### ISSUE TITLE
Swiftwolf's Ring will not fly

### ISSUE THREAD

**Issue by Andoxin00** [sinkillerj/ProjectE#1067]
I have just crafted a Swiftwolf ring and a klein star. I charged the klein star with around 10,000 EMC, but the ring will not fly. I am aware you have to double tap jump but that does not do it. I can enable the reflect enemies but not any other commands for it. (Projectile, ect.)

I am on version: ProjectE-1.7.10-PE1.9.3h

**Comment by sinkillerj** [comment]
Could you provide a pastebin'd log, or at the minimum a mods list? We have been working around flight conflicts with other mods lately so that may have something to do with it.

**Comment by Andoxin00** [comment]
I do not know where to find the log that you are requesting but here is my basic list of mods I have installed:

Treecapitator
Lucky Block
aether2
Biomes O' Plenty
buildcraft
Carpenter's Blocks
chocolatequest
CodeChickenCore
COFHCore
coroutil
Damage-Indicators
gilded-games-util
Hats
iChunUtil
industrialcraft
LootBags
Mantle
NetherOres
NotEnoughItems
Optifine
PortalGun
ProjectE
Railcraft
Reis-Minimap
TConstruct
Thaumcraft
ThermalDynamics
Thermal-Expansion
ThermalFoundation
TheWingsOfAlfheim
twilightforest
weather2

(Like I said, if you tell me where the log would be at, I would gladly post it.

**Comment by shobu9** [comment]
*It seems to affect when morph Fligth is on.

**Comment by Andoxin00** [comment]
What mod would that be a part of? I see no option to turn that off?

**Comment by MoonKill** [comment]
Can confirm.
Here is my modlist (taken from a crash log).
http://pastebin.com/0s8cxXHD

**Comment by Andoxin00** [comment]
Will this mean that we will have an updated version fixing this for 1.7.10? Or will we just have to remove a certain mod?

**Comment by shobu9** [comment]
Its not only when dimension changes, its also when the player gets a new fligth method, Same thing happens if you have the hurricane boots + the Flugel Tiara from botania +mana

**Comment by Andoxin00** [comment]
Fixed.
It apparently occurs whenever you have a conflicting flight item, even  when not active. (I had the Wings mod)
Also changing dimensions can cause this bug as well. (As pointed out in #1044) 

This thread can now close.

**Comment by williewillus** [comment]
Wait, this is not fixed?
We've just identified the cause, not fixed the bug, unless this sort of problem is unfixable (i don't know, I don't use other mods' flight options much)

**Comment by Andoxin00** [comment]
I think it is out of (our) control to pinpoint how to fix. I just recommend removing any mods that include flight capabilities till we can continue this issue. We've pinpointed the area, and for me, that's as close as I think we will get for now. I would fix it if I could, but I am not a dev. I will re-open for any continued help needed with this issue, but I am dropping out of this conversation.
