### ISSUE TITLE
[1.16.5] Forge 36.1.10+ and CraftTweaker compatibility

### ISSUE THREAD

**Issue by Bass2style** [sinkillerj/ProjectE#2119]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): PE1.0.1B

Exact Forge version: 36.1.10 and above

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): no logs

Steps to reproduce:

1. launch a modpack running Forge 36.1.10+ with ProjectE and  CraftTweaker in it, and, it's not running,
it says that you need CraftTweaker 7.1.0.79, but that i'm using 7.1.0. (i use actually 7.1.0.239)

What I expected to happen:
running when using necessary versions. xD

What happened instead:
not running.

**Comment by pupnewfster** [comment]
What happens if you use forge 36.1.9. I wonder if there is some weirdness with the optional version check fix

**Comment by Bass2style** [comment]
mods are working normaly with Forge 36.1.9 and less, it's due to the change introduced in Forge 36.1.10, TheOneProbe got same issue, and Chargers mod also, TOP is now fixed, but ProjectE and Chargers are still affected.

**Comment by pupnewfster** [comment]
In theory updating CrT to the latest version should fix it as there was a bug in their built jars that was only declaring the version as 7.1.0

**Comment by kreezxil** [comment]
I'm on forge 36.1.13 and i have crafttweaker 7.1.0.241 installed and I get this issue. Seems projectE has a fixed upper limit.

![image](https://user-images.githubusercontent.com/3880072/116012531-970edd80-a5f0-11eb-992c-01361f062c2f.png)

**Comment by kreezxil** [comment]
Forge build 36.1.10 does not resolve this issue, just tried it.

**Comment by kreezxil** [comment]
Alright Forge Build 36.1.6 allows us to  have build 244 of CraftTweaker and ProjectE, so it's an issue introduced in the later forge builds after .6

**Comment by Bass2style** [comment]
build .244 of CraftTweaker seems working. with Forge 36.1.13.
