### ISSUE TITLE
1.18.2 - Dark/Red Matter Furnace does not process everything in inventory automatically. 

### ISSUE THREAD

**Issue by Eleiyas** [sinkillerj/ProjectE#2187]
**Tickets that do not conform to this template will be closed without comment**

Exact ProjectE version (do not say "latest", "latest on Curse", or similar): 
ProjectE-1.18.2-PE1.0.1

Exact Forge version:
40.0.52 

Link to crash log (please use a paste site, do not attach the .txt or paste the log inline): 
N/A, not a crash.

Steps to reproduce:

1. Fill up a Dark Matter or Red Matter Furnace with ores.
2. Put some sort of fuel
3. Furnace processes first 64 ores, then hangs and doesn't process rest of inventory
4. Click on a stack of ores
5. Furnace then takes another stack and processes.

What I expected to happen:
Dark/Red Matter Furnace processes all 6-7 stacks of ores without manual input needed.

What happened instead:
Dark/Red Matter Furnace "hangs" after first stack, then requires player to click on anything in the inventory to then continue processing (rinse/repeat for each stack).

**Comment by nayfaan** [comment]
I'm noticing the same problem in the latest 1.16.5 version (PE1.0.2). Just wanna ask would this "fixed in dev" apply to the next 1.16.5 update too?

**Comment by Flexico** [comment]
Still happening in version MC_1.18.2 PE_1.0.1, with relays as well!
