### ISSUE TITLE
EMC discrepancy and an old EE2 options

### ISSUE THREAD

**Issue by zortag** [sinkillerj/ProjectE#426]
i see items from different mods sharing the same ore dictionary entry (es ingotOsmium or ingotBronze) will have different EMC values.
i also notice some EMC values added through command line have the same issue.

the original EE2 had a "%cost" option for bypass abuses on servers (cobblegen in relay). evalutate to add it (ie: cost 10% = a 100emc item cost 100 to be taken from tablet but give 90 when burned), decimal are always rounded to the lower (ie: cobblestone = 1emc burned at 10% cost gives 0,9emc, so nothing is added to the tablet emc amount)

**Comment by PiggyWhiskey** [comment]
I do like the idea of a cost option.

**Comment by Carbon-Ghost** [comment]
The EMC discrepancy is a major issue, especially for modpack makers !!! Can this be fixed in priority please ?

**Comment by MaPePeR** [comment]
@Carbon-Ghost are you using the latest version of ProjectE? A lot of EMC discrepancy got fixed with the latest updates.

At the moment it should works like this:
If a recipe uses an oredicted ingredient it picks the smallest from the possible oredict-items. If it uses a specific item it just uses the value for that specific item.

As a modpack author its kind of your job to remove these yourself. This is kind of the deal. We cannot generate emc values for all possibilities.

**Comment by Carbon-Ghost** [comment]
Well, RC tin & copper still have some problems unfortunately, and I have no idea how to fix this... except by removing the emc value.

**Comment by MaPePeR** [comment]
Could you describe the problem in more detail?

**Comment by Carbon-Ghost** [comment]
Nvm, latest latest version of Project E fix it... Even though the version I was using had already the graph ;P

**Comment by Kolatra** [comment]
Closing this issue as it seems to be fixed.

**Comment by Kolatra** [comment]
"Old EE2 option" is continued at #618.
